# netlify.toml - Alternative configuration

[build]
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"

# Catch-all redirect - sab kuch API function ko bhej do
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  conditions = {Role = [""], Country = [""]}

# Ya phir specific patterns
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200